# Generated by Django 5.1.15 on 2026-07-28 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField()),
                ('preventive_suggestions', models.JSONField(default=list)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='patients.patient')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.labreport')),
            ],
            options={
                'verbose_name_plural': 'Health summaries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestigationAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigation_key', models.CharField(db_index=True, max_length=64)),
                ('investigation_name', models.CharField(max_length=200)),
                ('current_value', models.FloatField(null=True)),
                ('current_unit', models.CharField(blank=True, max_length=50)),
                ('current_status', models.CharField(default='unknown', max_length=20)),
                ('previous_value', models.FloatField(blank=True, null=True)),
                ('oldest_value', models.FloatField(blank=True, null=True)),
                ('trend', models.CharField(default='stable', max_length=30)),
                ('severity', models.CharField(default='low', max_length=20)),
                ('rate_of_change', models.FloatField(blank=True, null=True)),
                ('possible_clinical_meaning', models.TextField(blank=True)),
                ('possible_causes', models.TextField(blank=True)),
                ('possible_complications', models.TextField(blank=True)),
                ('urgency_level', models.CharField(default='routine', max_length=20)),
                ('confidence_score', models.FloatField(default=0.7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='patients.patient')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='reports.labreport')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('patient', 'investigation_key')},
            },
        ),
        migrations.CreateModel(
            name='TrendSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigation_key', models.CharField(max_length=64)),
                ('series', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_snapshots', to='patients.patient')),
            ],
            options={
                'unique_together': {('patient', 'investigation_key')},
            },
        ),
    ]
