# Generated by Django 5.1.15 on 2026-07-28 18:52

import apps.reports.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=apps.reports.models.report_upload_to)),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('hospital_name', models.CharField(blank=True, max_length=255)),
                ('doctor_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('duplicate', 'Duplicate')], default='pending', max_length=20)),
                ('ocr_raw_text', models.TextField(blank=True)),
                ('processing_error', models.TextField(blank=True)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='patients.patient')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigation_key', models.CharField(db_index=True, max_length=64)),
                ('investigation_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('kft', 'Kidney Function Test'), ('urine', 'Urine Test'), ('cbc', 'Complete Blood Count'), ('lft', 'Liver Function Test'), ('diabetes', 'Diabetes'), ('lipid', 'Lipid Profile'), ('vitals', 'Vitals'), ('other', 'Other')], default='other', max_length=20)),
                ('raw_value', models.CharField(max_length=100)),
                ('numeric_value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('standardized_value', models.FloatField(blank=True, null=True)),
                ('standardized_unit', models.CharField(blank=True, max_length=50)),
                ('reference_range', models.CharField(blank=True, max_length=100)),
                ('reference_low', models.FloatField(blank=True, null=True)),
                ('reference_high', models.FloatField(blank=True, null=True)),
                ('status_flag', models.CharField(choices=[('normal', 'Normal'), ('low', 'Low'), ('high', 'High'), ('critical', 'Critical'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='reports.labreport')),
            ],
            options={
                'ordering': ['category', 'investigation_name'],
            },
        ),
        migrations.AddIndex(
            model_name='labreport',
            index=models.Index(fields=['patient', 'report_date'], name='reports_lab_patient_24bda1_idx'),
        ),
        migrations.AddIndex(
            model_name='labreport',
            index=models.Index(fields=['file_hash'], name='reports_lab_file_ha_effde1_idx'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['investigation_key', 'report'], name='reports_lab_investi_c60ecf_idx'),
        ),
    ]
