# Generated by Django 5.1.15 on 2026-07-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='extracted_patient_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='labreport',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Demo/sample data — excluded from real-patient clinical analysis by default.'),
        ),
        migrations.AddField(
            model_name='labreport',
            name='ocr_message',
            field=models.TextField(blank=True, help_text='Human-readable extraction status for the user.'),
        ),
        migrations.AddField(
            model_name='labreport',
            name='ocr_quality',
            field=models.CharField(blank=True, default='', help_text='good | partial | poor | failed', max_length=20),
        ),
        migrations.AddField(
            model_name='labresult',
            name='confidence_score',
            field=models.FloatField(default=0.0, help_text='0–1 extraction confidence from OCR/parsing. Not a clinical confidence.'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='extraction_status',
            field=models.CharField(choices=[('extracted', 'Extracted'), ('uncertain', 'Uncertain — needs review'), ('not_available', 'Unable to Extract')], default='extracted', max_length=20),
        ),
        migrations.AddField(
            model_name='labresult',
            name='needs_review',
            field=models.BooleanField(default=False, help_text='True when OCR quality is uncertain or fields are unreadable.'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='reference_source',
            field=models.CharField(choices=[('report', 'From report'), ('none', 'No range on report')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='status_flag',
            field=models.CharField(choices=[('normal', 'Normal'), ('low', 'Low'), ('high', 'High'), ('critical', 'Critical'), ('unknown', 'Unknown'), ('not_available', 'Not Available')], default='unknown', max_length=20),
        ),
    ]
